# Generated by Django 6.0.5 on 2026-05-24 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('client', models.CharField(blank=True, max_length=255)),
                ('auditor', models.CharField(blank=True, max_length=255)),
                ('project_type', models.CharField(choices=[('normal', 'Normal'), ('nycecc', 'NYC ECC'), ('ashrae', 'ASHRAE 90.1')], default='normal', max_length=20)),
                ('building_type', models.CharField(blank=True, choices=[('k12', 'K-12'), ('higher_ed', 'Higher Ed'), ('office', 'Office'), ('municipal', 'Municipal'), ('healthcare', 'Healthcare'), ('retail', 'Retail'), ('industrial', 'Industrial'), ('warehouse', 'Warehouse'), ('residential', 'Residential'), ('mixed_use', 'Mixed Use'), ('other', 'Other')], max_length=30)),
                ('square_feet', models.PositiveIntegerField(blank=True, null=True)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('hvac_type', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('utility', models.CharField(blank=True, max_length=255)),
                ('egrid_subregion', models.CharField(blank=True, max_length=50)),
                ('climate_zone', models.CharField(blank=True, max_length=20)),
                ('savings_model', models.CharField(blank=True, max_length=100)),
                ('baseline_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('emergency_lighting_strategy', models.CharField(blank=True, max_length=100)),
                ('room_type_hours_overrides', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('family', models.CharField(blank=True, max_length=100)),
                ('wattage_options', models.JSONField(blank=True, default=list)),
                ('cct_options', models.JSONField(blank=True, default=list)),
                ('dlc_listed', models.BooleanField(default=False)),
                ('em_options', models.JSONField(blank=True, default=list)),
                ('demand_response', models.BooleanField(default=False)),
                ('dimming_range', models.CharField(blank=True, max_length=50)),
                ('image_url', models.URLField(blank=True)),
                ('spec_sheet_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_family', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('accessory_type', models.CharField(blank=True, choices=[('goof_ring', 'Goof Ring'), ('trim', 'Trim'), ('mounting_plate', 'Mounting Plate'), ('socket_kit', 'Socket Kit'), ('other', 'Other')], max_length=30)),
                ('image_url', models.URLField(blank=True)),
                ('spec_sheet_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Product accessories',
            },
        ),
        migrations.CreateModel(
            name='CatalogModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=100)),
                ('suffix_code', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['family', 'sort_order'],
                'unique_together': {('family', 'suffix_code')},
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='audit.building')),
            ],
            options={
                'ordering': ['sort_order', 'level'],
            },
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='floor_plans/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='floor_plans/')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('floor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plan', to='audit.floor')),
            ],
        ),
        migrations.CreateModel(
            name='LightLevelReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('footcandles', models.DecimalField(decimal_places=2, max_digits=8)),
                ('measured_at', models.CharField(choices=[('floor', 'Floor'), ('30aff', '30" AFF'), ('surface', 'Surface')], default='floor', max_length=20)),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='light_levels', to='audit.floorplan')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('room_type', models.CharField(blank=True, max_length=100)),
                ('zone_label', models.CharField(blank=True, max_length=100)),
                ('pin_code', models.CharField(blank=True, max_length=50)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('square_feet', models.PositiveIntegerField(blank=True, null=True)),
                ('mount_height', models.CharField(blank=True, max_length=50)),
                ('ceiling_type', models.CharField(blank=True, max_length=100)),
                ('hours_override', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('wiring_three_way', models.BooleanField(default=False)),
                ('wiring_ab_switching', models.BooleanField(default=False)),
                ('wiring_no_neutral', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='audit.floor')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior')], default='interior', max_length=20)),
                ('facility', models.CharField(blank=True, max_length=255)),
                ('floor', models.CharField(blank=True, max_length=100)),
                ('space_zone', models.CharField(blank=True, max_length=255)),
                ('fixture_id', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('wattage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('mount_height', models.CharField(blank=True, max_length=50)),
                ('switch_type', models.CharField(blank=True, choices=[('toggle', 'Toggle'), ('wireless', 'Wireless Switch'), ('keyed', 'Keyed Switch'), ('rocker', 'Rocker'), ('scene', 'Scene Selector/Keypad'), ('dimmer', 'Dimmer'), ('sensor_switch', 'Sensor Switch'), ('low_voltage', 'Low Voltage'), ('none', 'None')], max_length=30)),
                ('controls', models.CharField(blank=True, max_length=255)),
                ('mount_type', models.CharField(blank=True, choices=[('surface', 'Surface'), ('wall', 'Wall'), ('pendant', 'Pendant'), ('threaded_rod', 'Threaded Rod'), ('chain', 'Chain'), ('aircraft_cable', 'Aircraft Cable'), ('kindorf', 'Kindorf'), ('recessed', 'Recessed'), ('knuckle', 'Knuckle'), ('trunnion', 'Trunnion'), ('bracket', 'Bracket'), ('slipfitter', 'Slipfitter'), ('tenon', 'Tenon'), ('wall_mount', 'Wall-Mount'), ('pole_mount', 'Pole-Mount')], max_length=30)),
                ('optic', models.CharField(blank=True, choices=[('type_ii', 'Type II'), ('type_iii', 'Type III'), ('type_iv', 'Type IV'), ('type_v', 'Type V')], max_length=20)),
                ('flag_integral_sensor', models.BooleanField(default=False)),
                ('flag_embb', models.BooleanField(default=False)),
                ('flag_air_return', models.BooleanField(default=False)),
                ('flag_wire_guard', models.BooleanField(default=False)),
                ('flag_volt_480', models.BooleanField(default=False)),
                ('flag_em_gen', models.BooleanField(default=False)),
                ('flag_photocell', models.BooleanField(default=False)),
                ('flag_twistlock_pc', models.BooleanField(default=False)),
                ('flag_wet_location', models.BooleanField(default=False)),
                ('flag_dark_sky', models.BooleanField(default=False)),
                ('ctrl_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='audit.room')),
            ],
            options={
                'verbose_name_plural': 'Log entries',
            },
        ),
        migrations.CreateModel(
            name='FloorPlanPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('polygon', models.JSONField(blank=True, default=list)),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='audit.floorplan')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pins', to='audit.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('voice_memo', models.FileField(blank=True, null=True, upload_to='voice_memos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_notes', to='audit.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='room_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='audit.room')),
            ],
        ),
        migrations.CreateModel(
            name='SpecItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('relamp', 'Re-lamp'), ('kit', 'Kit'), ('new_fixture', 'New Fixture'), ('custom', 'Custom'), ('switch', 'Switch/Control')], max_length=20)),
                ('model_string', models.CharField(blank=True, max_length=255)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('wattage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cct', models.CharField(blank=True, max_length=20)),
                ('switch_recommendation', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_items', to='audit.logentry')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audit.catalogproduct')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
