# Generated by Django 6.0.5 on 2026-05-24 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_building_project_alter_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='audit.project'),
        ),
    ]
