# Generated by Django 6.0.5 on 2026-05-24 18:28

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_building_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productaccessory',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productaccessory',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='specitem',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specitem',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.CreateModel(
            name='AuditVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('version_number', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('published_to_ipad', 'Published To Ipad')], default='draft', max_length=30)),
                ('source_payload', models.JSONField()),
                ('is_current', models.BooleanField(default=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_versions', to='audit.building')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='floor',
            name='audit_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit.auditversion'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='audit_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit.auditversion'),
        ),
        migrations.AddField(
            model_name='room',
            name='audit_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit.auditversion'),
        ),
    ]
