# Generated by Django 6.0.5 on 2026-05-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_productaccessory_created_productaccessory_modified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditversion',
            options={'ordering': ['-version_number']},
        ),
        migrations.AlterField(
            model_name='auditversion',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='auditversion',
            name='source_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='auditversion',
            name='version_number',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='auditversion',
            unique_together={('building', 'version_number')},
        ),
    ]
