# Generated by Django 6.0.5 on 2026-05-24 18:45

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warn', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('dismissed', 'Dismissed')], default='active', max_length=10)),
                ('dismissed_reason', models.TextField(blank=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('source_run_id', models.PositiveIntegerField(blank=True, null=True)),
                ('audit_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_flags', to='audit.auditversion')),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_flags', to=settings.AUTH_USER_MODEL)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_flags', to='audit.logentry')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
