# Generated by Django 6.0.5 on 2026-05-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_remove_auditflag_source_run_id_agentrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditversion',
            name='client_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
