# Generated by Django 6.0.5 on 2026-05-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0012_auditversion_client_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='client_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
