# Generated by Django 6.0.5 on 2026-05-26 09:35

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0014_photo_upload_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('prompt_text', models.TextField()),
                ('agent_type', models.CharField(choices=[('audit_review', 'Audit Review'), ('chatbot', 'Chatbot')], default='audit_review', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
